version: '3'
services:
  zeppelin:
    image: apache/zeppelin:0.7.2
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/zeppelin/logs
      - ./notebook:/zeppelin/notebook
    environment:
      -ZEPPELIN_LOG_DIR: /zeppelin/logs
      -ZEPPELIN_NOTEBOOK_DIR: /zeppelin/notebook